### PR TITLE
Added array and set support

### PR DESCRIPTION
**Pull request by ystrict**
Hi, here I've implemented ability to correctly parse Array and Set entities. Both of them can be provided by OPA.

### CODE REVIEW

**Comment by tgeens** [comment]
Thanks for the contribution.

I was going to ask for a test, but it looks like we don't have any tests in here :roll_eyes:

**Comment by tgeens** [comment]
@ystrict do you have an example policy where you encountered this missing support for sets ?

**Comment by ystrict** [comment]
> @ystrict do you have an example policy where you encountered this missing support for sets ?

Yep, here is an example:
test {
    num := input.entity.number
    num in {"one", "two", "three"}
}

**Comment by tgeens** [comment]
Can you add a test in `OpaClientIntegrationTests` ?

**Comment by ystrict** [comment]
> Can you add a test in `OpaClientIntegrationTests` ?
done

**Pull request merged**
